"""
Libellés CIM-10 pour l'enrichissement des rapports (PDF/Excel/JSON).
Miroir de dmpi-frontend-main-v2/app/services/cim10Service.ts — même liste,
seul le code et le libellé sont repris ici (le chapitre n'est pas utilisé
côté rapports).
"""

CIM10_LABELS: dict[str, str] = {
    "E10": "Diabète sucré de type 1",
    "E11": "Diabète sucré de type 2",
    "E14": "Diabète sucré, sans précision",
    "E66": "Obésité",
    "E50": "Carence en vitamine A",
    "E64": "Séquelles de malnutrition",
    "I10": "Hypertension essentielle (primaire)",
    "I11": "Cardiopathie hypertensive",
    "I20": "Angine de poitrine",
    "I21": "Infarctus aigu du myocarde",
    "I50": "Insuffisance cardiaque",
    "I63": "Infarctus cérébral",
    "I64": "Accident vasculaire cérébral sans précision",
    "I83": "Varices des membres inférieurs",
    "J00": "Rhinopharyngite aiguë (rhume banal)",
    "J06.9": "Infection aiguë des voies respiratoires supérieures, sans précision",
    "J18": "Pneumopathie, sans précision",
    "J20": "Bronchite aiguë",
    "J45": "Asthme",
    "J22": "Infection aiguë des voies respiratoires inférieures, sans précision",
    "J98.9": "Trouble respiratoire, sans précision",
    "A00": "Choléra",
    "A01": "Fièvres typhoïde et paratyphoïde",
    "A06": "Amibiase",
    "A09": "Diarrhée et gastro-entérite d'origine infectieuse présumée",
    "A15": "Tuberculose respiratoire",
    "A59": "Trichomonase",
    "B50": "Paludisme à Plasmodium falciparum",
    "B53": "Autres formes de paludisme confirmées par examen parasitologique",
    "B54": "Paludisme, sans précision",
    "B20": "Maladie due au VIH entraînant des maladies infectieuses et parasitaires",
    "B24": "Maladie due au VIH, sans précision",
    "B37": "Candidose",
    "B77": "Ascaridiose",
    "K29.7": "Gastrite, sans précision",
    "K21": "Maladie de reflux gastro-oesophagien",
    "K40": "Hernie inguinale",
    "K70": "Maladie alcoolique du foie",
    "K74": "Fibrose et cirrhose hépatiques",
    "K80": "Lithiase biliaire",
    "K90": "Malabsorption intestinale",
    "N18": "Maladie rénale chronique",
    "N39.0": "Infection des voies urinaires, siège non précisé",
    "N40": "Hyperplasie bénigne de la prostate",
    "O10": "Hypertension préexistante compliquant la grossesse",
    "O14": "Hypertension gravidique avec protéinurie significative",
    "O24": "Diabète sucré survenant au cours de la grossesse",
    "O80": "Accouchement spontané par le siège",
    "D50": "Anémie par carence en fer",
    "D51": "Anémie par carence en vitamine B12",
    "D57": "Troubles dus à la drépanocytose",
    "D64": "Autres anémies",
    "M10": "Goutte",
    "M19": "Autres arthropathies",
    "M54.5": "Lombalgie basse",
    "M79.3": "Panniculite",
    "L20": "Dermatite atopique",
    "L50": "Urticaire",
    "L60.0": "Ongle incarné",
    "G35": "Sclérose en plaques",
    "G40": "Épilepsie",
    "G43": "Migraine",
    "G47.0": "Troubles de l'endormissement et du maintien du sommeil",
    "F32": "Épisode dépressif",
    "F41": "Autres troubles anxieux",
    "F20": "Schizophrénie",
    "S00": "Traumatisme superficiel de la tête",
    "S72": "Fracture du fémur",
    "T14.0": "Plaie d'une région non précisée du corps",
    "C22": "Tumeur maligne du foie",
    "C34": "Tumeur maligne des bronches et du poumon",
    "C50": "Tumeur maligne du sein",
    "H10": "Conjonctivite",
    "H26": "Autres cataractes",
    "H40": "Glaucome",
    "H60": "Otite externe",
    "H66": "Otite moyenne suppurée et non précisée",
    "J02": "Pharyngite aiguë",
    "J03": "Amygdalite aiguë",
    "J01": "Sinusite aiguë",
    "R50": "Fièvre d'étiologie inconnue",
    "R51": "Céphalée",
    "R05": "Toux",
    "R07": "Douleur du pharynx et de la poitrine",
    "R10": "Douleurs abdominales et pelviennes",
    "R55": "Syncope et collapsus",
    "Z00": "Examen médical général",
}


def libelle_cim10(code: str | None) -> str:
    if not code:
        return "Non renseigné"
    return CIM10_LABELS.get(code, code)
