// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/medecin": {
    params: {};
  };
  "/medecin/patients": {
    params: {};
  };
  "/medecin/consultations": {
    params: {};
  };
  "/medecin/ordonnances": {
    params: {};
  };
  "/medecin/agenda": {
    params: {};
  };
  "/medecin/dossier/:npi": {
    params: {
      "npi": string;
    };
  };
  "/medecin/dossier/:npi/modifier": {
    params: {
      "npi": string;
    };
  };
  "/medecin/dossier/:npi/consultation/nouvelle": {
    params: {
      "npi": string;
    };
  };
  "/medecin/dossier/:npi/ordonnance/nouvelle": {
    params: {
      "npi": string;
    };
  };
  "/infirmier": {
    params: {};
  };
  "/infirmier/patients": {
    params: {};
  };
  "/infirmier/constantes": {
    params: {};
  };
  "/infirmier/traitements": {
    params: {};
  };
  "/infirmier/dossier/:npi": {
    params: {
      "npi": string;
    };
  };
  "/patient": {
    params: {};
  };
  "/patient/ordonnances": {
    params: {};
  };
  "/patient/resultats": {
    params: {};
  };
  "/patient/rendez-vous": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/supervision": {
    params: {};
  };
  "/admin/statistiques": {
    params: {};
  };
  "/superadmin": {
    params: {};
  };
  "/superadmin/audit": {
    params: {};
  };
  "/superadmin/etablissements": {
    params: {};
  };
  "/superadmin/utilisateurs": {
    params: {};
  };
  "/superadmin/monitoring": {
    params: {};
  };
  "/superadmin/rapports": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/medecin" | "/medecin/patients" | "/medecin/consultations" | "/medecin/ordonnances" | "/medecin/agenda" | "/medecin/dossier/:npi" | "/medecin/dossier/:npi/modifier" | "/medecin/dossier/:npi/consultation/nouvelle" | "/medecin/dossier/:npi/ordonnance/nouvelle" | "/infirmier" | "/infirmier/patients" | "/infirmier/constantes" | "/infirmier/traitements" | "/infirmier/dossier/:npi" | "/patient" | "/patient/ordonnances" | "/patient/resultats" | "/patient/rendez-vous" | "/admin" | "/admin/supervision" | "/admin/statistiques" | "/superadmin" | "/superadmin/audit" | "/superadmin/etablissements" | "/superadmin/utilisateurs" | "/superadmin/monitoring" | "/superadmin/rapports";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "components/layout/AppShell.tsx": {
    id: "components/layout/AppShell";
    page: "/" | "/medecin" | "/medecin/patients" | "/medecin/consultations" | "/medecin/ordonnances" | "/medecin/agenda" | "/medecin/dossier/:npi" | "/medecin/dossier/:npi/modifier" | "/medecin/dossier/:npi/consultation/nouvelle" | "/medecin/dossier/:npi/ordonnance/nouvelle" | "/infirmier" | "/infirmier/patients" | "/infirmier/constantes" | "/infirmier/traitements" | "/infirmier/dossier/:npi" | "/patient" | "/patient/ordonnances" | "/patient/resultats" | "/patient/rendez-vous" | "/admin" | "/admin/supervision" | "/admin/statistiques" | "/superadmin" | "/superadmin/audit" | "/superadmin/etablissements" | "/superadmin/utilisateurs" | "/superadmin/monitoring" | "/superadmin/rapports";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/medecin/dashboard.tsx": {
    id: "routes/medecin/dashboard";
    page: "/medecin";
  };
  "routes/medecin/patients.tsx": {
    id: "routes/medecin/patients";
    page: "/medecin/patients";
  };
  "routes/medecin/consultations.tsx": {
    id: "routes/medecin/consultations";
    page: "/medecin/consultations";
  };
  "routes/medecin/ordonnances.tsx": {
    id: "routes/medecin/ordonnances";
    page: "/medecin/ordonnances";
  };
  "routes/medecin/agenda.tsx": {
    id: "routes/medecin/agenda";
    page: "/medecin/agenda";
  };
  "routes/medecin/dossier.$npi.tsx": {
    id: "routes/medecin/dossier.$npi";
    page: "/medecin/dossier/:npi";
  };
  "routes/medecin/dossier.$npi.modifier.tsx": {
    id: "routes/medecin/dossier.$npi.modifier";
    page: "/medecin/dossier/:npi/modifier";
  };
  "routes/medecin/nouvelle-consultation.$npi.tsx": {
    id: "routes/medecin/nouvelle-consultation.$npi";
    page: "/medecin/dossier/:npi/consultation/nouvelle";
  };
  "routes/medecin/nouvelle-ordonnance.$npi.tsx": {
    id: "routes/medecin/nouvelle-ordonnance.$npi";
    page: "/medecin/dossier/:npi/ordonnance/nouvelle";
  };
  "routes/infirmier/dashboard.tsx": {
    id: "routes/infirmier/dashboard";
    page: "/infirmier";
  };
  "routes/infirmier/patients.tsx": {
    id: "routes/infirmier/patients";
    page: "/infirmier/patients";
  };
  "routes/infirmier/constantes.tsx": {
    id: "routes/infirmier/constantes";
    page: "/infirmier/constantes";
  };
  "routes/infirmier/traitements.tsx": {
    id: "routes/infirmier/traitements";
    page: "/infirmier/traitements";
  };
  "routes/infirmier/dossier.$npi.tsx": {
    id: "routes/infirmier/dossier.$npi";
    page: "/infirmier/dossier/:npi";
  };
  "routes/patient/dashboard.tsx": {
    id: "routes/patient/dashboard";
    page: "/patient";
  };
  "routes/patient/ordonnances.tsx": {
    id: "routes/patient/ordonnances";
    page: "/patient/ordonnances";
  };
  "routes/patient/resultats.tsx": {
    id: "routes/patient/resultats";
    page: "/patient/resultats";
  };
  "routes/patient/rendez-vous.tsx": {
    id: "routes/patient/rendez-vous";
    page: "/patient/rendez-vous";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/supervision.tsx": {
    id: "routes/admin/supervision";
    page: "/admin/supervision";
  };
  "routes/admin/statistiques.tsx": {
    id: "routes/admin/statistiques";
    page: "/admin/statistiques";
  };
  "routes/superadmin/dashboard.tsx": {
    id: "routes/superadmin/dashboard";
    page: "/superadmin";
  };
  "routes/superadmin/audit.tsx": {
    id: "routes/superadmin/audit";
    page: "/superadmin/audit";
  };
  "routes/superadmin/etablissements.tsx": {
    id: "routes/superadmin/etablissements";
    page: "/superadmin/etablissements";
  };
  "routes/superadmin/utilisateurs.tsx": {
    id: "routes/superadmin/utilisateurs";
    page: "/superadmin/utilisateurs";
  };
  "routes/superadmin/monitoring.tsx": {
    id: "routes/superadmin/monitoring";
    page: "/superadmin/monitoring";
  };
  "routes/superadmin/rapports.tsx": {
    id: "routes/superadmin/rapports";
    page: "/superadmin/rapports";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "components/layout/AppShell": typeof import("./app/components/layout/AppShell.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/medecin/dashboard": typeof import("./app/routes/medecin/dashboard.tsx");
  "routes/medecin/patients": typeof import("./app/routes/medecin/patients.tsx");
  "routes/medecin/consultations": typeof import("./app/routes/medecin/consultations.tsx");
  "routes/medecin/ordonnances": typeof import("./app/routes/medecin/ordonnances.tsx");
  "routes/medecin/agenda": typeof import("./app/routes/medecin/agenda.tsx");
  "routes/medecin/dossier.$npi": typeof import("./app/routes/medecin/dossier.$npi.tsx");
  "routes/medecin/dossier.$npi.modifier": typeof import("./app/routes/medecin/dossier.$npi.modifier.tsx");
  "routes/medecin/nouvelle-consultation.$npi": typeof import("./app/routes/medecin/nouvelle-consultation.$npi.tsx");
  "routes/medecin/nouvelle-ordonnance.$npi": typeof import("./app/routes/medecin/nouvelle-ordonnance.$npi.tsx");
  "routes/infirmier/dashboard": typeof import("./app/routes/infirmier/dashboard.tsx");
  "routes/infirmier/patients": typeof import("./app/routes/infirmier/patients.tsx");
  "routes/infirmier/constantes": typeof import("./app/routes/infirmier/constantes.tsx");
  "routes/infirmier/traitements": typeof import("./app/routes/infirmier/traitements.tsx");
  "routes/infirmier/dossier.$npi": typeof import("./app/routes/infirmier/dossier.$npi.tsx");
  "routes/patient/dashboard": typeof import("./app/routes/patient/dashboard.tsx");
  "routes/patient/ordonnances": typeof import("./app/routes/patient/ordonnances.tsx");
  "routes/patient/resultats": typeof import("./app/routes/patient/resultats.tsx");
  "routes/patient/rendez-vous": typeof import("./app/routes/patient/rendez-vous.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/supervision": typeof import("./app/routes/admin/supervision.tsx");
  "routes/admin/statistiques": typeof import("./app/routes/admin/statistiques.tsx");
  "routes/superadmin/dashboard": typeof import("./app/routes/superadmin/dashboard.tsx");
  "routes/superadmin/audit": typeof import("./app/routes/superadmin/audit.tsx");
  "routes/superadmin/etablissements": typeof import("./app/routes/superadmin/etablissements.tsx");
  "routes/superadmin/utilisateurs": typeof import("./app/routes/superadmin/utilisateurs.tsx");
  "routes/superadmin/monitoring": typeof import("./app/routes/superadmin/monitoring.tsx");
  "routes/superadmin/rapports": typeof import("./app/routes/superadmin/rapports.tsx");
};