"""baseline schema

Revision ID: 0b4babda729b
Revises: 
Create Date: 2026-07-15 16:50:41.473771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4babda729b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_email', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('npi_concerne', sa.String(length=10), nullable=True),
    sa.Column('statut_action', sa.String(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_npi_concerne'), 'audit_logs', ['npi_concerne'], unique=False)
    op.create_index(op.f('ix_audit_logs_utilisateur_email'), 'audit_logs', ['utilisateur_email'], unique=False)
    op.create_table('delegations_acces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegant_email', sa.String(), nullable=False),
    sa.Column('beneficiaire_email', sa.String(), nullable=False),
    sa.Column('npi_patient', sa.String(length=10), nullable=False),
    sa.Column('motif', sa.String(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_acces_beneficiaire_email'), 'delegations_acces', ['beneficiaire_email'], unique=False)
    op.create_index(op.f('ix_delegations_acces_delegant_email'), 'delegations_acces', ['delegant_email'], unique=False)
    op.create_index(op.f('ix_delegations_acces_id'), 'delegations_acces', ['id'], unique=False)
    op.create_index(op.f('ix_delegations_acces_npi_patient'), 'delegations_acces', ['npi_patient'], unique=False)
    op.create_table('demandes_acces_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('telephone_contact', sa.String(), nullable=False),
    sa.Column('demandeur_email', sa.String(), nullable=False),
    sa.Column('etablissement_id', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('motif_rejet', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandes_acces_patient_demandeur_email'), 'demandes_acces_patient', ['demandeur_email'], unique=False)
    op.create_index(op.f('ix_demandes_acces_patient_id'), 'demandes_acces_patient', ['id'], unique=False)
    op.create_index(op.f('ix_demandes_acces_patient_npi'), 'demandes_acces_patient', ['npi'], unique=False)
    op.create_table('departement',
    sa.Column('id_dep', sa.Integer(), nullable=False),
    sa.Column('lib_dep', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_dep')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('npi_patient', sa.String(length=10), nullable=True),
    sa.Column('etablissement_id', sa.String(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('derniere_connexion_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('commune',
    sa.Column('id_com', sa.Integer(), nullable=False),
    sa.Column('lib_com', sa.String(length=250), nullable=False),
    sa.Column('id_dep', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dep'], ['departement.id_dep'], ),
    sa.PrimaryKeyConstraint('id_com')
    )
    op.create_table('arrondissement',
    sa.Column('id_arrond', sa.Integer(), nullable=False),
    sa.Column('lib_arrond', sa.String(length=250), nullable=False),
    sa.Column('id_com', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_com'], ['commune.id_com'], ),
    sa.PrimaryKeyConstraint('id_arrond')
    )
    op.create_table('quartier',
    sa.Column('id_quart', sa.Integer(), nullable=False),
    sa.Column('lib_quart', sa.String(length=250), nullable=False),
    sa.Column('id_arrond', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_arrond'], ['arrondissement.id_arrond'], ),
    sa.PrimaryKeyConstraint('id_quart')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quartier')
    op.drop_table('arrondissement')
    op.drop_table('commune')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('departement')
    op.drop_index(op.f('ix_demandes_acces_patient_npi'), table_name='demandes_acces_patient')
    op.drop_index(op.f('ix_demandes_acces_patient_id'), table_name='demandes_acces_patient')
    op.drop_index(op.f('ix_demandes_acces_patient_demandeur_email'), table_name='demandes_acces_patient')
    op.drop_table('demandes_acces_patient')
    op.drop_index(op.f('ix_delegations_acces_npi_patient'), table_name='delegations_acces')
    op.drop_index(op.f('ix_delegations_acces_id'), table_name='delegations_acces')
    op.drop_index(op.f('ix_delegations_acces_delegant_email'), table_name='delegations_acces')
    op.drop_index(op.f('ix_delegations_acces_beneficiaire_email'), table_name='delegations_acces')
    op.drop_table('delegations_acces')
    op.drop_index(op.f('ix_audit_logs_utilisateur_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_npi_concerne'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
