services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: dmpi-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dmpi-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: dmpi-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - dmpi-network
    restart: unless-stopped
    volumes:
      - kafkadata:/bitnami/kafka

  postgres:
    image: postgres:15-alpine
    container_name: dmpi-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD manquant dans .env}
      - POSTGRES_DB=${POSTGRES_DB:-dmpi_db}
    networks:
      - dmpi-network
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: dmpi-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?MONGO_INITDB_ROOT_USERNAME manquant dans .env}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?MONGO_INITDB_ROOT_PASSWORD manquant dans .env}
    networks:
      - dmpi-network
    restart: unless-stopped
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dmpi-fastapi
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD manquant dans .env}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-dmpi_db}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:?MONGO_INITDB_ROOT_USERNAME manquant dans .env}:${MONGO_INITDB_ROOT_PASSWORD:?MONGO_INITDB_ROOT_PASSWORD manquant dans .env}@mongodb:27017/dmpi_db?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-120}
      - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      - UPLOAD_DIR=/app/uploads
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres
      - mongodb
      - kafka
    networks:
      - dmpi-network
    restart: unless-stopped

networks:
  dmpi-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
  kafkadata:
  uploads:
